version: "2"
volumes:
    traph-data:
    mongo-data: 
services:
  backend:
    image: scpomedialab/hyphe_backend:latest
    build: .
    links:
     - "mongo:mongo"
     - "crawler:crawler"
    environment:
     - HYPHE_MONGODB_HOST=mongo
     - HYPHE_MONGODB_PORT=27017
     - HYPHE_CRAWLER_HOST=crawler
     - HYPHE_CRAWLER_PORT=6800
     - HYPHE_TRAPH_DATAPATH=/app/traph-data
    ports:
     - "6978:6978"
    volumes:
      - traph-data:/app/traph-data
  frontend:
    image: scpomedialab/hyphe_frontend:latest
    build: ./hyphe_frontend
    ports:
      - "80:80"
    links:
      - "backend:backend"
  crawler:
    image: scpomedialab/hyphe_crawler:latest
    build: 
       context: .
       dockerfile: ./hyphe_backend/crawler/Dockerfile
    links:
      - "mongo:mongo"
  mongo:
    image: mongo:3.0
    volumes:
      - mongo-data:/data/db
